/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ["./src/**/*.{js,jsx,ts,tsx}"],
    theme: {
        extend: {
            colors: {
				"white-fb":"#FBFBFB",
				"white-f2":"#F2F2F2",
				"white-a2":"#A2A2A2",
				"white-e3":"#E3E3E3",
				"white-border":"#DBDBDB",
				"white-CC":"#CCCCCC",
				"white-f2f4":"#F2F4F4",
				"black-30": "#303030",
				"blue-00a5e0":"#00A5E0",
				"gray-b3":"#B3B3B3",
				"white-f9": "#F9F9F9",
				"blue-b5":"#B5CFE4",
				"blue-85":"#85A8C1",
				"blue-87":"#87AECE",
				"blue-b5c":"#B5CFE4",
				"blue-a7":"#A7C9E1",
				"green-8e":"#8EAD7B",
				"gray-d7":"#D7D7D7",
				"gray-62":"#626262",
				"gray-EC":"#ECECEC",
				"brown-77":"#776643",
				"gray-ad":"#626262",
				"bronse-50":"#504E4E",
				"bronse-33":"#333333",
				"bronse-78":"#786643",
				"social":" #ADADAD"
			},
            screens: {
				'mb': {'max': '640px'},
				'mbl': {'max': '850px'},
				'crd': {'max': '950px'},
				'mini': {'max': '460px'},
				'mdl': {'max': '1240px'},
				'mdlm': {'min': '1240px'},
				'mdsr': {'max': '1690px'},
				'mmdsr': {'min': '1690px'},
				'mdlx': {'max': '1450px'},
				'mdlxm': {'min': '1450px'},
				'mdxxl': {'max': '1750px'},
				'sup': {'max': '1850px'},
			},
            fontFamily: {
                'comis': "'Commissioner', 'sans-serif'",
                'inter': "'Inter', 'sans-serif'",
                'raleway': "'Raleway', 'sans-serif'",
                'roboto': "'Roboto', 'sans-serif'",
            },
			maxHeight:{
				'smallCard':'356px',
				'longWCard':'356px',
				'longHCard':'711px',
				
				'slider':'692px',
				'sliderResponsive':'0px',
			},
			maxWidth:{
				'smallCard':'540px',
				'smallCardRes':'281px',
				'longWCard':'1100px',
				'longHCard':'540px',
			},
			minHeight:{
				'smallCard':'356px',
				'longWCard':'356px',
				'longHCard':'711px',
				'slider':'692px',
				'sliderResponsive':'0px',
			},
			minWidth:{
				'smallCard':'540px',
				'longWCard':'1100px',
				'longHCard':'540px',
				'smallCardRes':'281px',
			},
			letterSpacing:{
				'casing': '-0.01em',
			},
			backgroundImage: {
				'bg-req': "url('/src/Assets/request/request.png')",
			},
        },
    },
    plugins: [],
}
